#!/bin/bash

set -e

name=$1
fullFrequency=$2
origDir=$3
deviceUUID=$4
mountPoint=$5
backupDir_RelToMountPoint=$6

date >> /home/nathdwek/backupLogs/"$name"Times.log;

mount UUID="$deviceUUID" "$mountPoint" -o defaults > /home/nathdwek/backupLogs/"$name".log;

duplicity --no-encryption --name "$name" --full-if-older-than "$fullFrequency" "$origDir" file://"$mountPoint"/"$backupDir_RelToMountPoint" >> /home/nathdwek/backupLogs/"$name".log;

duplicity remove-all-but-n-full 1 --force file://"$mountPoint"/"$backupDir_RelToMountPoint" >> /home/nathdwek/backupLogs/"$name".log;

umount $mountPoint >> /home/nathdwek/backupLogs/"$name".log;

echo "Good" >>  /home/nathdwek/backupLogs/"$name"Times.log;


