#!/bin/bash

set -e

name=$1
fullFrequency=$2
origDir=$3
backupUrl=$4

date >> backupLogsDir__/"$name"Times.log;

duplicity --no-encryption --name "$name" --full-if-older-than "$fullFrequency" "$origDir" "$backupUrl" > backupLogsDir__/"$name".log;

duplicity remove-all-inc-of-but-n-full 2 --force "$backupUrl" >> backupLogsDir__/"$name".log;

echo "Good" >>  backupLogsDir__/"$name"Times.log;


