#!/bin/bash

set -e

name=$1
origDir=$2
deviceUUID=$3
mountPoint=$4
backupDir_RelToMountPoint=$5

date >> backupLogsDir__/"$name"Times.log;

mount UUID="$deviceUUID" "$mountPoint" -o defaults > backupLogsDir__/"$name".log;

duplicity --no-encryption --name "$name" "$origDir" file://"$mountPoint"/"$backupDir_RelToMountPoint" >> backupLogsDir__/"$name".log;

umount $mountPoint >> backupLogsDir__/"$name".log;

echo "reached end" >>  backupLogsDir__/"$name"Times.log;
