#!/bin/bash

set -e

name=$1
fullFrequency=$2
origDir=$3
deviceUUID=$4
mountPoint=$5
backupDir_RelToMountPoint=$6

date >> backupLogsDir__/"$name"Times.log;

mount UUID="$deviceUUID" "$mountPoint" -o defaults > backupLogsDir__/"$name".log;

duplicity --no-encryption --name "$name" --full-if-older-than "$fullFrequency" "$origDir" file://"$mountPoint"/"$backupDir_RelToMountPoint" >> backupLogsDir__/"$name".log;

duplicity remove-all-inc-of-but-n-full 2 --force file://"$mountPoint"/"$backupDir_RelToMountPoint" >> backupLogsDir__/"$name".log;

umount $mountPoint >> backupLogsDir__/"$name".log;

echo "reached end" >>  backupLogsDir__/"$name"Times.log;
