#!/bin/bash

set -e

name=$1
origDir=$2
deviceUUID=$3
mountPoint=$4
backupDir_RelToMountPoint=$5

date >> /home/nathdwek/backupLogs/"$name"Times.log;

mount UUID="$deviceUUID" "$mountPoint" -o defaults > /home/nathdwek/backupLogs/"$name".log;

duplicity --no-encryption --name "$name" "$origDir" file://"$mountPoint"/"$backupDir_RelToMountPoint" >> /home/nathdwek/backupLogs/"$name".log;

umount $mountPoint >> /home/nathdwek/backupLogs/"$name".log;

echo "reached End" >>  /home/nathdwek/backupLogs/"$name"Times.log;


