#!/bin/bash

set -e

if [[ $# -ne 1 ]]; then
   echo "This is cueFlacSplit: quick script to split a flac file given a cue file. Requires one parameter: file to split (cue file must have the same name). Extensions are taken care of." > /dev/stderr
   exit 2
fi

f=$1;
d=$(mktemp -d  cueFlacSplit.XXX)

shnsplit -o flac -q -d "$d/" -f "${f%.*}.cue" -t "%n_%t" "${f%.*}.flac";
if [ -f "$d/00_pregap.flac" ]; then rm "$d/00_pregap.flac"; fi
for o in "$d/*.flac"; do cuetag "${f%.*}.cue" $o;done;
