#!/bin/bash
d=$(mktemp -d --tmpdir=$HOME/storage/Musique/FFOutput/ hqFlacToAlac.XXX)
for f in ./*.flac; do avconv -v warning -analyzeduration 100000000 -i "$f" -vn -c:a alac -ar 48000 -sample_fmt s16p "$d/${f%.*}.m4a"; done
#-vn: do not bother with video stream if present
#16bit/48kHz because must fit on an ipod
